language: python
python:
  - "2.7"
git:
  depth: 1
# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py --quiet install
  - mv pymatgen-db pmgdb
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - pymatgen-dev@mit.edu
    on_success: change
    on_failure: always
